### ISSUE TITLE
Error when make dsn.String() as connect string

### ISSUE THREAD

**Issue by kokorolx** [rvflash/awql-driver#2]
```
AdwordsID:v201806:false:false:false|DeveloperToken|AccessToken|ClientID|ClientSecret|RefreshToken
panic: driver: bad connection
```
When i use 
```
dsn := awql.NewDsn("AdwordsID")
dsn.AdwordsID = "AdwordsID"
  dsn.APIVersion = "v201806"
  dsn.DeveloperToken = "DeveloperToken"
  dsn.ClientID = "ClientID"
  dsn.ClientSecret = "ClientSecret"
  dsn.RefreshToken = "RefreshToken"
 dsn.AccessToken = "AccessToken"
```
i recieve this message:
`panic: driver: bad connection`
When i print the `dsn.String()`
```
AdwordsID:v201806:false:false:false|DeveloperToken|AccessToken|ClientID|ClientSecret|RefreshToken
```
what is `:false:false:false` ???

if remove it, my project will run ok.?

Can you help me?

**Comment by rvflash** [comment]
Hi @kokorolee,

It's normal, all given inputs are wrong (fake token, wrong Adwords ID format, etc.). 
Try for example with valid data in a DSN's struct with just these fields: AdwordsID, DeveloperToken and AccessToken.
If you do not have a valid AccessToken yet, use valid data for AdwordsID, DeveloperToken, ClientID, ClientSecret and RefreshToken (keep empty the other struct fields).

Regarding your last question, the 3 booleans refer to the value of these fields in the DSN's struct : SkipColumnHeader, SupportsZeroImpressions and UseRawEnumValues.
